---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	prepare_agent(prepare_agent)
	initialize(initialize)
	main_agent_startup(main_agent_startup)
	startup_tool_result(startup_tool_result)
	startup_failed(startup_failed)
	docling(docling)
	await_ready_work(await_ready_work)
	main_agent_route_images(main_agent_route_images)
	route_images_directly(route_images_directly)
	vlm(vlm)
	main_agent_route_outputs(main_agent_route_outputs)
	route_outputs_directly(route_outputs_directly)
	formatter(formatter)
	map_database_fields(map_database_fields)
	write_database(write_database)
	finish_run(finish_run)
	set_vlm_routes(set_vlm_routes)
	set_formatter_routes(set_formatter_routes)
	ensure_redis(ensure_redis)
	create_vlm_queues(create_vlm_queues)
	create_formatter_queues(create_formatter_queues)
	schedule_models(schedule_models)
	start_docling(start_docling)
	diagnose_redis(diagnose_redis)
	start_redis_service(start_redis_service)
	inspect_startup_resources(inspect_startup_resources)
	abort_startup(abort_startup)
	invalid_startup_tool(invalid_startup_tool)
	__end__([<p>__end__</p>]):::last
	__start__ --> prepare_agent;
	abort_startup --> startup_tool_result;
	await_ready_work -. &nbsp;thinking_enabled&nbsp; .-> main_agent_route_images;
	await_ready_work -. &nbsp;direct&nbsp; .-> route_images_directly;
	create_formatter_queues --> startup_tool_result;
	create_vlm_queues --> startup_tool_result;
	diagnose_redis --> startup_tool_result;
	docling -. &nbsp;thinking_enabled&nbsp; .-> main_agent_route_images;
	docling -. &nbsp;direct&nbsp; .-> route_images_directly;
	ensure_redis --> startup_tool_result;
	formatter --> map_database_fields;
	initialize --> main_agent_startup;
	inspect_startup_resources --> startup_tool_result;
	invalid_startup_tool --> startup_tool_result;
	main_agent_route_images --> vlm;
	main_agent_route_outputs --> formatter;
	main_agent_startup -.-> abort_startup;
	main_agent_startup -.-> create_formatter_queues;
	main_agent_startup -.-> create_vlm_queues;
	main_agent_startup -.-> diagnose_redis;
	main_agent_startup -.-> ensure_redis;
	main_agent_startup -.-> inspect_startup_resources;
	main_agent_startup -.-> invalid_startup_tool;
	main_agent_startup -.-> schedule_models;
	main_agent_startup -.-> set_formatter_routes;
	main_agent_startup -.-> set_vlm_routes;
	main_agent_startup -.-> start_docling;
	main_agent_startup -.-> start_redis_service;
	main_agent_startup -.-> startup_failed;
	map_database_fields --> write_database;
	prepare_agent --> initialize;
	route_images_directly --> vlm;
	route_outputs_directly --> formatter;
	schedule_models --> startup_tool_result;
	set_formatter_routes --> startup_tool_result;
	set_vlm_routes --> startup_tool_result;
	start_docling --> startup_tool_result;
	start_redis_service --> startup_tool_result;
	startup_tool_result -.-> docling;
	startup_tool_result -.-> main_agent_startup;
	startup_tool_result -.-> startup_failed;
	vlm -. &nbsp;thinking_enabled&nbsp; .-> main_agent_route_outputs;
	vlm -. &nbsp;direct&nbsp; .-> route_outputs_directly;
	write_database -. &nbsp;more_work&nbsp; .-> await_ready_work;
	write_database -. &nbsp;finished&nbsp; .-> finish_run;
	finish_run --> __end__;
	startup_failed --> __end__;
	main_agent_startup -.-> main_agent_startup;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
